### ISSUE TITLE
Error while compilation

### ISSUE THREAD

**Issue by kpbicka** [ichebyki/yoRadio.vs#3]
Compiling .pio/build/esp-wrover-kit/src/src/core/controls.cpp.o
src/src/core/controls.cpp: In function 'void controlsEvent(bool, int8_t)':
src/src/core/controls.cpp:485:49: error: 'VOLUME_STEP' was not declared in this scope
       int nv = config.store.volume + volDelta * VOLUME_STEP;
                                                                            ^~~~~~~~~~~
src/src/core/controls.cpp:485:49: note: suggested alternative: 'VOLUME'
       int nv = config.store.volume + volDelta * VOLUME_STEP;
                                                                            ^~~~~~~~~~~
                                                 VOLUME
*** [.pio/build/esp-wrover-kit/src/src/core/controls.cpp.o] Error 1

**Comment by lagosha1967** [comment]
Add these strings to myoptions.h from the original one:
#define VOLUME_STEP           1 // 1 is default
#define VOLUME_LOGARITHMIC true // logarithmic volume change
